version: "3.9"

services:
  wol-relay:
    image: ghcr.io/alleynz/homelab-wol-relay:latest
    container_name: wol-relay
    restart: unless-stopped

    volumes:
      # Change the left-hand path to wherever you keep your config
      - ./config:/config:ro
